title: RT-SEG
description: Reasoning Trace Segmentation Framework
markdown: kramdown

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Optional, but nice
search_enabled: true